In [1]:
import pandas as pd
import numpy as np
import talib

# Read NVIDIA stock price data
file_path = "/home/jesse/Projects/RL_Testing/Q_Learning/Training/nvidia_stock_prices.csv"
df = pd.read_csv(file_path)

# Check Date format
df["Date"] = pd.to_datetime(df["Date"])
df.set_index("Date", inplace=True)

# Take a look
df.head()

                Open      High       Low     Close      Volume
Date
2004-01-02  0.196417  0.199083  0.192333  0.192333   436416000
2004-01-05  0.195250  0.199917  0.193500  0.198583   575292000
2004-01-06  0.198000  0.209417  0.197083  0.206667  1093344000
2004-01-07  0.204333  0.209500  0.202917  0.208500   673032000
2004-01-08  0.211083  0.212083  0.207250  0.209250   433752000

In [2]:
# 计Calculate Indexes

# 1.（SMA）
df['SMA_20'] = talib.SMA(df['Close'], timeperiod=20)
df['SMA_50'] = talib.SMA(df['Close'], timeperiod=50)

# 2.（EMA）
df['EMA_20'] = talib.EMA(df['Close'], timeperiod=20)
df['EMA_50'] = talib.EMA(df['Close'], timeperiod=50)

# 3.（MACD）
df['MACD'], df['MACD_signal'], df['MACD_hist'] = talib.MACD(df['Close'], fastperiod=12, slowperiod=26, signalperiod=9)

# 4.（RSI）
df['RSI_14'] = talib.RSI(df['Close'], timeperiod=14)

# 5.（Bollinger Bands）
df['BB_upper'], df['BB_middle'], df['BB_lower'] = talib.BBANDS(df['Close'], timeperiod=20, nbdevup=2, nbdevdn=2, matype=0)

# 6.（ATR）
df['ATR_14'] = talib.ATR(df['High'], df['Low'], df['Close'], timeperiod=14)

# 7.（MFI）
df['MFI_14'] = talib.MFI(df['High'], df['Low'], df['Close'], df['Volume'], timeperiod=14)

# 8.（Stochastic Oscillator）
df['slowk'], df['slowd'] = talib.STOCH(df['High'], df['Low'], df['Close'], fastk_period=14, slowk_period=3, slowd_period=3)

# Take a look
df = df.dropna()  # Drop NaN value
print(df.tail())

                 Open       High        Low      Close     Volume    SMA_20  \
Date
2023-12-22  49.195000  49.382999  48.466999  48.830002  252507000  47.73215
2023-12-26  48.967999  49.599998  48.959999  49.278999  244200000  47.78400
2023-12-27  49.511002  49.680000  49.084999  49.417000  233648000  47.86380
2023-12-28  49.643002  49.883999  49.411999  49.521999  246587000  47.93290
2023-12-29  49.813000  49.997002  48.750999  49.521999  389293000  48.07050

              SMA_50     EMA_20     EMA_50      MACD  MACD_signal  MACD_hist  \
Date
2023-12-22  46.28386  48.049748  46.885619  0.633659     0.563715   0.069945
2023-12-26  46.36022  48.166820  46.979477  0.655050     0.581982   0.073068
2023-12-27  46.42666  48.285885  47.075067  0.675353     0.600656   0.074697
2023-12-28  46.53834  48.403610  47.171025  0.691939     0.618913   0.073027
2023-12-29  46.68486  48.510123  47.263220  0.697049     0.634540   0.062509

               RSI_14   BB_upper  BB_middle   BB_lower    ATR_14     MFI_14  \
Date
2023-12-22  55.345442  50.178101   47.73215  45.286199  1.346709  68.185252
2023-12-26  57.239771  50.313522   47.78400  45.254478  1.305515  67.553658
2023-12-27  57.831871  50.491741   47.86380  45.235859  1.254764  73.746585
2023-12-28  58.304947  50.657169   47.93290  45.208631  1.198853  73.322614
2023-12-29  58.304947  50.823768   48.07050  45.317232  1.202220  65.871212

                slowk      slowd
Date
2023-12-22  66.506589  72.237522
2023-12-26  73.117971  70.462282
2023-12-27  74.974402  71.532987
2023-12-28  78.728523  75.606965
2023-12-29  79.792529  77.831818

In [3]:
# Save DataFrame to CSV
output_file_path = "/home/jesse/Projects/RL_Testing/Q_Learning/Training/NVDA_full.csv"
df.to_csv(output_file_path)

print(f"Dataframe saved to : {output_file_path}")

Dataframe saved to : /home/jesse/Projects/RL_Testing/Q_Learning/Training/NVDA_full.csv

In [4]:
import pandas as pd
import talib

# 1. Read Apple stock price data
file_path = "/home/jesse/Projects/RL_Testing/Q_Learning/Testing/apple_stock_prices.csv"
# df = pd.read_csv(file_path, parse_dates=["Date"], index_col="Date")
df = pd.read_csv(file_path)

# 2. Rename and re-arrange order of column names
df = df.rename(columns={
    "Date" : "Date",
    "Open": "Open",
    "High": "High",
    "Low": "Low",
    "Close": "Close",
    "Volume": "Volume"
})
df = df[["Date", "Open", "High", "Low", "Close", "Volume"]]

df.head()

         Date      Open      High       Low     Close     Volume
0  1980-12-12  0.128348  0.128906  0.128348  0.128348  469033600
1  1980-12-15  0.122210  0.122210  0.121652  0.121652  175884800
2  1980-12-16  0.113281  0.113281  0.112723  0.112723  105728000
3  1980-12-17  0.115513  0.116071  0.115513  0.115513   86441600
4  1980-12-18  0.118862  0.119420  0.118862  0.118862   73449600

In [5]:
# 计Calculate Indexes

# 1. (SMA）
df['SMA_20'] = talib.SMA(df['Close'], timeperiod=20)
df['SMA_50'] = talib.SMA(df['Close'], timeperiod=50)

# 2.（EMA）
df['EMA_20'] = talib.EMA(df['Close'], timeperiod=20)
df['EMA_50'] = talib.EMA(df['Close'], timeperiod=50)

# 3.（MACD）
df['MACD'], df['MACD_signal'], df['MACD_hist'] = talib.MACD(df['Close'], fastperiod=12, slowperiod=26, signalperiod=9)

# 4.（RSI）
df['RSI_14'] = talib.RSI(df['Close'], timeperiod=14)

# 5.（Bollinger Bands）
df['BB_upper'], df['BB_middle'], df['BB_lower'] = talib.BBANDS(df['Close'], timeperiod=20, nbdevup=2, nbdevdn=2, matype=0)

# 6.（ATR）
df['ATR_14'] = talib.ATR(df['High'], df['Low'], df['Close'], timeperiod=14)

# 7.（MFI）
df['MFI_14'] = talib.MFI(df['High'], df['Low'], df['Close'], df['Volume'], timeperiod=14)

# 8.（Stochastic Oscillator）
df['slowk'], df['slowd'] = talib.STOCH(df['High'], df['Low'], df['Close'], fastk_period=14, slowk_period=3, slowd_period=3)

# Take a look
df = df.dropna()  # Drop NaN values
print(df.tail())

             Date        Open        High         Low       Close    Volume  \
11102  2024-12-27  257.829987  258.700012  253.059998  255.589996  42355300
11103  2024-12-30  252.229996  253.500000  250.750000  252.199997  35557500
11104  2024-12-31  252.440002  253.279999  249.429993  250.419998  39480700
11105  2025-01-02  248.929993  249.100006  241.820007  243.850006  55558000
11106  2025-01-03  243.369995  244.179993  241.889999  243.860001  15135053

           SMA_20      SMA_50      EMA_20      EMA_50  ...  MACD_signal  \
11102  248.524500  236.893599  248.590801  239.832882  ...     5.667139
11103  249.267999  237.294599  248.934534  240.317867  ...     5.665606
11104  249.809499  237.602999  249.076007  240.714029  ...     5.549921
11105  249.869500  237.750399  248.578292  240.837008  ...     5.251281
11106  249.912000  237.910399  248.128931  240.955557  ...     4.841816

       MACD_hist     RSI_14    BB_upper   BB_middle    BB_lower    ATR_14  \
11102   0.459237  67.575020  260.426425  248.524500  236.622574  4.079470
11103  -0.006132  60.185319  260.088496  249.267999  238.447502  4.133794
11104  -0.462742  56.680397  259.680818  249.809499  239.938180  4.113523
11105  -1.194558  46.026161  259.579286  249.869500  240.159714  4.433985
11106  -1.637862  46.042777  259.508092  249.912000  240.315909  4.280843

          MFI_14      slowk      slowd
11102  72.265318  89.825340  95.002646
11103  66.742356  72.004529  86.322724
11104  61.167942  51.590085  71.139985
11105  53.945912  30.150995  51.248536
11106  55.342485  18.378583  33.373221

[5 rows x 21 columns]

In [6]:
# Save DataFrame to CSV
output_file_path = "/home/jesse/Projects/RL_Testing/Q_Learning/Testing/AAPL_full.csv"
df.to_csv(output_file_path)

print(f"dataframe saved to: {output_file_path}")

dataframe saved to: /home/jesse/Projects/RL_Testing/Q_Learning/Testing/AAPL_full.csv